framework:
    messenger:
        transports:

        routing:

        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - 'App\Common\Infrastructure\Messenger\Middleware\DbTransactionMiddleware'
                    - 'App\Common\Infrastructure\Messenger\Middleware\DomainEventDispatcherMiddleware'

            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - 'App\Common\Infrastructure\Messenger\Middleware\DomainEventDispatcherMiddleware'

            query.bus: ~