framework:
    messenger:
        transports:

        routing:

        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - 'App\Common\Infrastructure\Messenger\Middleware\DbTransactionMiddleware'

            query.bus: ~