framework:
    messenger:
        serializer:
            symfony_serializer:
                format: json
                context: { }

        transports:
            async_priority_high:
                dsn: '%env(AMQP_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    vhost: '%env(AMQP_VHOST)%'
                    auto_setup: false
                    exchange:
                        name: high
                        default_publish_routing_key: high
                    queues:
                        high_messages: ~

            async_priority_low:
                dsn: '%env(AMQP_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    vhost: '%env(AMQP_VHOST)%'
                    auto_setup: false
                    exchange:
                        name: low
                        default_publish_routing_key: low
                    queues:
                        low_messages: ~

        routing:
            'App\Modules\OwnerAccount\Application\SendConfirmationEmail\SendConfirmationEmailCommand': async_priority_low

        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - 'App\Common\Infrastructure\Messenger\Middleware\DbTransactionMiddleware'
                    - 'App\Common\Infrastructure\Messenger\Middleware\DomainEventDispatcherMiddleware'

            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - 'App\Common\Infrastructure\Messenger\Middleware\DomainEventDispatcherMiddleware'

            query.bus: ~