services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Common\:
        resource: '../src/Common/'

imports:
    - { resource: '../src/Modules/OwnerAccount/Infrastructure/Configuration/Resources/services.yml' }